server:
  port: 9090
spring:
  security:
    enabled: false
  application:
    name: League-Application
  datasource:
    url: jdbc:mysql://localhost:3306/leagueApplication
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
