server:
  port: 9090

spring:
  application:
    name:League_Application
  datasource:
    url: jdbc:postgresql://localhost:5433/leagueApplication
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
